# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: mintakson.com
email: mintak.son@gmail.com
description: Mintak Son, who is software engineer.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mintakson.com" # the base hostname & protocol for your site
twitter_username: smintfreely
github_username:  mintakson

# Build settings
markdown: kramdown
